/*****************************/
// !!!  AUTOGENERATED FILE  !!!
// !!! DO NOT EDIT MANUALLY !!!
/*****************************/

import com.google.protobuf.gradle.*
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    `java-library`

    %%plugins%%
}

val javaVersion = JavaVersion.VERSION_17
java {
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    // withSourcesJar()
}

tasks.withType<KotlinCompile> {
    kotlinOptions.jvmTarget = javaVersion.toString()
    dependsOn(tasks.named("generateProto"))
}

repositories {
    mavenCentral() 
}

dependencies {
    %%libraries%%

    %%artifacts%%
}

val protoSrcDir: Directory = layout.projectDirectory.dir("gradlegen/proto")
val protoGenDir: Provider<Directory> = layout.buildDirectory.dir("generated/source/proto/main")
val kotlinSrcDir: Directory = layout.projectDirectory.dir("src/kotlin")

sourceSets {
    main {
        java {
            setSrcDirs(listOf(
                kotlinSrcDir.asFile.path,
                protoGenDir.map{it.asFile.path},
            ))
            setExcludes(listOf("**/test/*.kt"))
        }
        proto { 
            setSrcDirs(listOf(
                protoSrcDir.asFile.path,
            ))
        }
    }
    /*test {
        java {
            setSrcDirs(listOf("src/kotlin"))
            setIncludes(listOf("**/test/*.kt"))
        }
    }*/
}

protobuf {
    protoc {
        artifact = "${libs.protoc.compiler.get()}"
    }
    plugins {
        id("grpc") {
            artifact = "${libs.protoc.java.get()}"
        }
        id("grpckt") {
            artifact = "${libs.protoc.kotlin.get()}:jdk8@jar"
        }
    }
    generateProtoTasks {
        all().forEach {
            it.plugins {
                create("grpc")
                create("grpckt")
            }
            it.builtins {
                create("kotlin")
            }
        }
    }
}